project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: Project
        href: about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

